/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampusRouteImport } from './routes/campus'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FacultyRouteImport } from './routes/faculty'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutDisclosureRouteImport } from './routes/about.disclosure'
import { Route as AboutManagementRouteImport } from './routes/about.management'
import { Route as AboutPrincipalRouteImport } from './routes/about.principal'
import { Route as AboutVisionRouteImport } from './routes/about.vision'
import { Route as AcademicsIndexRouteImport } from './routes/academics.index'
import { Route as AcademicsTopicRouteImport } from './routes/academics.$topic'
import { Route as CampusIndexRouteImport } from './routes/campus.index'
import { Route as CampusFacilityRouteImport } from './routes/campus.$facility'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as AuthenticatedPortalAdminRouteImport } from './routes/_authenticated/portal.admin'
import { Route as AuthenticatedPortalParentRouteImport } from './routes/_authenticated/portal.parent'
import { Route as AuthenticatedPortalStudentRouteImport } from './routes/_authenticated/portal.student'
import { Route as AuthenticatedPortalTeacherRouteImport } from './routes/_authenticated/portal.teacher'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRoute = CampusRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRoute = FacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)
const AboutDisclosureRoute = AboutDisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => AboutRoute,
} as any)
const AboutManagementRoute = AboutManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AboutRoute,
} as any)
const AboutPrincipalRoute = AboutPrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => AboutRoute,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AboutRoute,
} as any)
const AcademicsIndexRoute = AcademicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademicsRoute,
} as any)
const AcademicsTopicRoute = AcademicsTopicRouteImport.update({
  id: '/$topic',
  path: '/$topic',
  getParentRoute: () => AcademicsRoute,
} as any)
const CampusIndexRoute = CampusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusRoute,
} as any)
const CampusFacilityRoute = CampusFacilityRouteImport.update({
  id: '/$facility',
  path: '/$facility',
  getParentRoute: () => CampusRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalAdminRoute =
  AuthenticatedPortalAdminRouteImport.update({
    id: '/portal/admin',
    path: '/portal/admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalParentRoute =
  AuthenticatedPortalParentRouteImport.update({
    id: '/portal/parent',
    path: '/portal/parent',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalStudentRoute =
  AuthenticatedPortalStudentRouteImport.update({
    id: '/portal/student',
    path: '/portal/student',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPortalTeacherRoute =
  AuthenticatedPortalTeacherRouteImport.update({
    id: '/portal/teacher',
    path: '/portal/teacher',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/campus': typeof CampusRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/resources': typeof ResourcesRoute
  '/about/disclosure': typeof AboutDisclosureRoute
  '/about/management': typeof AboutManagementRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/vision': typeof AboutVisionRoute
  '/academics/$topic': typeof AcademicsTopicRoute
  '/campus/$facility': typeof CampusFacilityRoute
  '/portal/login': typeof PortalLoginRoute
  '/about/': typeof AboutIndexRoute
  '/academics/': typeof AcademicsIndexRoute
  '/campus/': typeof CampusIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/parent': typeof AuthenticatedPortalParentRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/teacher': typeof AuthenticatedPortalTeacherRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/resources': typeof ResourcesRoute
  '/about/disclosure': typeof AboutDisclosureRoute
  '/about/management': typeof AboutManagementRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/vision': typeof AboutVisionRoute
  '/academics/$topic': typeof AcademicsTopicRoute
  '/campus/$facility': typeof CampusFacilityRoute
  '/portal/login': typeof PortalLoginRoute
  '/about': typeof AboutIndexRoute
  '/academics': typeof AcademicsIndexRoute
  '/campus': typeof CampusIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/portal/parent': typeof AuthenticatedPortalParentRoute
  '/portal/student': typeof AuthenticatedPortalStudentRoute
  '/portal/teacher': typeof AuthenticatedPortalTeacherRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRouteWithChildren
  '/academics': typeof AcademicsRouteWithChildren
  '/achievements': typeof AchievementsRoute
  '/activities': typeof ActivitiesRoute
  '/admissions': typeof AdmissionsRoute
  '/auth': typeof AuthRoute
  '/campus': typeof CampusRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/faculty': typeof FacultyRoute
  '/gallery': typeof GalleryRoute
  '/notices': typeof NoticesRoute
  '/resources': typeof ResourcesRoute
  '/about/disclosure': typeof AboutDisclosureRoute
  '/about/management': typeof AboutManagementRoute
  '/about/principal': typeof AboutPrincipalRoute
  '/about/vision': typeof AboutVisionRoute
  '/academics/$topic': typeof AcademicsTopicRoute
  '/campus/$facility': typeof CampusFacilityRoute
  '/portal/login': typeof PortalLoginRoute
  '/about/': typeof AboutIndexRoute
  '/academics/': typeof AcademicsIndexRoute
  '/campus/': typeof CampusIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/portal/admin': typeof AuthenticatedPortalAdminRoute
  '/_authenticated/portal/parent': typeof AuthenticatedPortalParentRoute
  '/_authenticated/portal/student': typeof AuthenticatedPortalStudentRoute
  '/_authenticated/portal/teacher': typeof AuthenticatedPortalTeacherRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/activities'
    | '/admissions'
    | '/auth'
    | '/campus'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/resources'
    | '/about/disclosure'
    | '/about/management'
    | '/about/principal'
    | '/about/vision'
    | '/academics/$topic'
    | '/campus/$facility'
    | '/portal/login'
    | '/about/'
    | '/academics/'
    | '/campus/'
    | '/portal/'
    | '/portal/admin'
    | '/portal/parent'
    | '/portal/student'
    | '/portal/teacher'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/activities'
    | '/admissions'
    | '/auth'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/resources'
    | '/about/disclosure'
    | '/about/management'
    | '/about/principal'
    | '/about/vision'
    | '/academics/$topic'
    | '/campus/$facility'
    | '/portal/login'
    | '/about'
    | '/academics'
    | '/campus'
    | '/portal'
    | '/portal/admin'
    | '/portal/parent'
    | '/portal/student'
    | '/portal/teacher'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/academics'
    | '/achievements'
    | '/activities'
    | '/admissions'
    | '/auth'
    | '/campus'
    | '/contact'
    | '/events'
    | '/faculty'
    | '/gallery'
    | '/notices'
    | '/resources'
    | '/about/disclosure'
    | '/about/management'
    | '/about/principal'
    | '/about/vision'
    | '/academics/$topic'
    | '/campus/$facility'
    | '/portal/login'
    | '/about/'
    | '/academics/'
    | '/campus/'
    | '/portal/'
    | '/_authenticated/portal/admin'
    | '/_authenticated/portal/parent'
    | '/_authenticated/portal/student'
    | '/_authenticated/portal/teacher'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRouteWithChildren
  AcademicsRoute: typeof AcademicsRouteWithChildren
  AchievementsRoute: typeof AchievementsRoute
  ActivitiesRoute: typeof ActivitiesRoute
  AdmissionsRoute: typeof AdmissionsRoute
  AuthRoute: typeof AuthRoute
  CampusRoute: typeof CampusRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FacultyRoute: typeof FacultyRoute
  GalleryRoute: typeof GalleryRoute
  NoticesRoute: typeof NoticesRoute
  ResourcesRoute: typeof ResourcesRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/disclosure': {
      id: '/about/disclosure'
      path: '/disclosure'
      fullPath: '/about/disclosure'
      preLoaderRoute: typeof AboutDisclosureRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/management': {
      id: '/about/management'
      path: '/management'
      fullPath: '/about/management'
      preLoaderRoute: typeof AboutManagementRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/principal': {
      id: '/about/principal'
      path: '/principal'
      fullPath: '/about/principal'
      preLoaderRoute: typeof AboutPrincipalRouteImport
      parentRoute: typeof AboutRoute
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof AboutRoute
    }
    '/academics/': {
      id: '/academics/'
      path: '/'
      fullPath: '/academics/'
      preLoaderRoute: typeof AcademicsIndexRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/academics/$topic': {
      id: '/academics/$topic'
      path: '/$topic'
      fullPath: '/academics/$topic'
      preLoaderRoute: typeof AcademicsTopicRouteImport
      parentRoute: typeof AcademicsRoute
    }
    '/campus/': {
      id: '/campus/'
      path: '/'
      fullPath: '/campus/'
      preLoaderRoute: typeof CampusIndexRouteImport
      parentRoute: typeof CampusRoute
    }
    '/campus/$facility': {
      id: '/campus/$facility'
      path: '/$facility'
      fullPath: '/campus/$facility'
      preLoaderRoute: typeof CampusFacilityRouteImport
      parentRoute: typeof CampusRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal/admin': {
      id: '/_authenticated/portal/admin'
      path: '/portal/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof AuthenticatedPortalAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/parent': {
      id: '/_authenticated/portal/parent'
      path: '/portal/parent'
      fullPath: '/portal/parent'
      preLoaderRoute: typeof AuthenticatedPortalParentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/student': {
      id: '/_authenticated/portal/student'
      path: '/portal/student'
      fullPath: '/portal/student'
      preLoaderRoute: typeof AuthenticatedPortalStudentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal/teacher': {
      id: '/_authenticated/portal/teacher'
      path: '/portal/teacher'
      fullPath: '/portal/teacher'
      preLoaderRoute: typeof AuthenticatedPortalTeacherRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalAdminRoute: typeof AuthenticatedPortalAdminRoute
  AuthenticatedPortalParentRoute: typeof AuthenticatedPortalParentRoute
  AuthenticatedPortalStudentRoute: typeof AuthenticatedPortalStudentRoute
  AuthenticatedPortalTeacherRoute: typeof AuthenticatedPortalTeacherRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalAdminRoute: AuthenticatedPortalAdminRoute,
  AuthenticatedPortalParentRoute: AuthenticatedPortalParentRoute,
  AuthenticatedPortalStudentRoute: AuthenticatedPortalStudentRoute,
  AuthenticatedPortalTeacherRoute: AuthenticatedPortalTeacherRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AboutRouteChildren {
  AboutDisclosureRoute: typeof AboutDisclosureRoute
  AboutManagementRoute: typeof AboutManagementRoute
  AboutPrincipalRoute: typeof AboutPrincipalRoute
  AboutVisionRoute: typeof AboutVisionRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutDisclosureRoute: AboutDisclosureRoute,
  AboutManagementRoute: AboutManagementRoute,
  AboutPrincipalRoute: AboutPrincipalRoute,
  AboutVisionRoute: AboutVisionRoute,
  AboutIndexRoute: AboutIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface AcademicsRouteChildren {
  AcademicsTopicRoute: typeof AcademicsTopicRoute
  AcademicsIndexRoute: typeof AcademicsIndexRoute
}

const AcademicsRouteChildren: AcademicsRouteChildren = {
  AcademicsTopicRoute: AcademicsTopicRoute,
  AcademicsIndexRoute: AcademicsIndexRoute,
}

const AcademicsRouteWithChildren = AcademicsRoute._addFileChildren(
  AcademicsRouteChildren,
)

interface CampusRouteChildren {
  CampusFacilityRoute: typeof CampusFacilityRoute
  CampusIndexRoute: typeof CampusIndexRoute
}

const CampusRouteChildren: CampusRouteChildren = {
  CampusFacilityRoute: CampusFacilityRoute,
  CampusIndexRoute: CampusIndexRoute,
}

const CampusRouteWithChildren =
  CampusRoute._addFileChildren(CampusRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRouteWithChildren,
  AcademicsRoute: AcademicsRouteWithChildren,
  AchievementsRoute: AchievementsRoute,
  ActivitiesRoute: ActivitiesRoute,
  AdmissionsRoute: AdmissionsRoute,
  AuthRoute: AuthRoute,
  CampusRoute: CampusRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FacultyRoute: FacultyRoute,
  GalleryRoute: GalleryRoute,
  NoticesRoute: NoticesRoute,
  ResourcesRoute: ResourcesRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
